development:
  domain: localhost:3000
  username: monikeradmin
  password: mynameiswhat

test:
  domain: test.host

production:
  domain: moniker.heroku.com
  username: monikeradmin
  password: mynameiswhat
