development:
  domain: localhost:3000
  username: username
  password: passwd
  
test:
  domain: test.host
  username: username
  password: passwd
  
production:
  domain: example.com
  username: username
  password: passwd
